name: Build (MacOS, Linux, Windows)

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [windows-latest, macOS-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - name: Install Rust Nightly Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
